
const Strings = {

    en: {

        "login": {
            "signIn": "Sign In",
            "userName": "User Name",
            "enterUserName": "Enter user name",
            "password": "Password",
            "enterPassword": "Enter password",
            "rememberMe": "Remember Me",
            "forgotPassword": "Forgot password ?",
            "dontHaveAnAccount": "Don't have an account?",
            "signUp": "Sign Up",
            "thisFieldIsRequired": "This field is required.",
            "invalidUserName": "Invalid user name",
            "invalidPassword": "Enter valid password",
            "english": "English",
            "arabic": "Arabic"
        },
        "header": {
            "login": "Login",
            "smartControl": "SMART CONTROL",
            "welcome": "Welcome",
            "guest": "Guest"
        },
        "dashboard": {
            "myTasks": "My Tasks",
            "licenses": "Licenses",
             "license":"LICENSES",
            "cases": "Cases",
             "case":"CASES",
            "campaign": "Campaign",
            "temporaryPermits": "Temporary Permits",
            "adhocTasks": "Adhoc Tasks",
            "foodAlerts": "Food Alerts",
            "completedTesk": "Completed Task",
            "history": "History / New Task",
            "search": "Search",
            "sort":"Sort By",
            "pleaseEnterText": "Please Enter Text"
        },
        "establishmentDetails": {
            "establishmentDetails": "Establishment Details",
            "establishmentName": "Establishment Name",
            "licenseSource": "License Source",
            "licenseStartDate": "License Start Date",
            "licenseEndDate": "License End Date",
            "licenseNumber": "License Number",
            "contactDetails": "Contact Details",
            "address": "Address",
            "area": "Area",
            "contact": "Contact",
            "efst": "EFST",
            "sector": "Sector",
            "print":"Print",
            "viewChecklist":"View Checklist",
            "createPdfMsg":"Create PDF",

        },
        "alertComponent": {
            "score": "Score",
            "description": "Description",
            "nonComplaince": "Non complaince",
        },
        "inspectionDetails": {
            "finalInspectionReport":"Final Inspection Report",
            "inspectionResult":"Inspection Result",
            "inspectionDetails": "Inspection Details",
            "inspectionDetailsbtn": "Inspection Details",
            "taskId": "Task ID",
            "taskType": "Task Type",
            "creationDate": "Creation Date",
            "businessActivity": "Business Activity",
            "subbusinessActivity": "Sub Business Activity",
            "description": "Description",
            "risk": "Risk",
            "sheduledDate": "Sheduled Date",
            "action": "Action",
            "startInpection": "Start Inspection",
            "inspectionNo": "Inspection No.",
            "acknowledge": 'Acknowledge'
        },
        "historyInspectionDetails": {
            "inspectionDetails": "Inspection Details",
            "inspectionNumber": "Inspection Number",
            "taskType": "Task Type",
            "creationDate": "Creation Date",
            "completionDate":"Completion Date",
            "status": "Status",
            "businessActivity": "Business Activity",
            "grade": "Grade",
            "description": "Description",
            "priority": "Priority",           
            "viewChecklist":"View CheckList"
        },
        "myTask": {
            "myTask": "MY TASKS",
            "inspectionId": "InspectionId",
            "type": "Type",
            "license": "License",
            "searchHere": "Search here"
        },
        "startInspection": {
            "startInpection": "START INSPECTION",
            "part1DesignAndStructureAndEquiment": "Part 1 :Design,Structure and Equiment",
            "updateSomething": "1.update something",
            "contactName": "Contact Name",
            "mobileNumber": "Mobile Number",
            "emiratesId": "Emirates Id",
            "evidence": "Evidence",
            "license": "License",
            "checklist": " Step 1: Checklist",
            "submission": "Step 3: Submission",
            "documentation": "Step 2: Documentation & Records",
            "checklistSubmittedSuccessfully": "Checklist Submitted Successfully",
            "checklistNotAvailable": "No Checklist",
            "condemnation": "Condemnation",
            "detention": "Detention",
            "sampling": "Sampling",
            "onHoldRequest": "On Hold Request",
            "requestforClosure": "Request for Closure",
            "finalResult": "Final Result",
            "finalInspectionResult": "Final Inspection Result",
            "totalScore": "Total Score :0",
            "grade": "Grade :E",
            "percentage": "Percentage :0",
            "calculate": "Calculate",
            "print": "Print",
            next: 'Next',
            back: 'Back'
        },
	"documentAndRecord":{
            signHere:"Please Sign Here",
            save:"Save",
            result:"Result",
            finalComment:"Final Comment",
            condemnation:"Condemnation",
            sampling:"Sampling",
            detention:"Detention",
            onHoldRequest:"On Hold Request",
            requestForClosure:"Request for Closure",
        },
        "contactList": {
            "contactList": "CONTACT LIST",
            "type": "Type",
            "name": "Name",
            "nationality": "Nationality",
            "mobileNumber": "Mobile Number",
            "relationship": "Relationship",
        },
        "action": {
            "action": "ACTION",
            "taskId": "Task ID",
            "establishment": "Establishment",
            "reason": "Reason",
            "comments": "Comments",
            "proposedDate": "Proposed Date",
            "submit": "Submit",
            "cancel": "Cancel"
        },
        "efstDetails": {
            "efstDetails": "EFST DETAILS",
            "foodHandlerId": "Food Handler ID",
            "emiratesId": "Emirates ID",
            "foodHandlerName": "Food Handler Name",
            "gender": "Gender",
            "passPercentage": "Pass Percentage",
            "nationality": "Nationality",
            "passortNumber": "Passort Number",
            "trained": "Trained",
            "certified": "Certified",
            "foodHandlerCount": "Food Handler Count",
            "noUpdates": "No Updates",
            "update": "Update",
        },
        "profile": {
            "profileDetails": "Profile Details",
            "guideManual": "Manuals/Guides",
            "inspectorName": "Inspector Name",
            "position": "Position",
            "inspectionArea": "Inspection Area",
            "unit": "Unit",
            "selectLanguage": "Select Language",
            "fileType": "File Type",
            "manualName": "Manual Name",
            "versionNumber": "Version Number"
        },
        "taskList": {
            "document": "Document",
            "staff": "Staff",
            "lastReport": "Last Report",
            "history": 'History',
            "directions": "Directions",
            "routineInspection": "Routine Inspection",
            "followUp": "FollowUp",
            "complaints": "Complaints",
            "license": "License",
            "foodAlerts": "FoodAlerts",
            "instantViolation": "Instant Violation",
            "adhocTasks": "Adhoc Task",
            "sampling": "Sampling",
            "condemnation": "Condemnation",
            "detention": "Detention",
            "closure": "Closure",
            "scheduled": "Scheduled",
            "adhoc": "Adhoc",
            about: "About",
            document: "Documents"
        },
        "detention": {
            "detention": "Detention",
            "condemnation": 'Condemnation',
            "recordNumber": 'Record No ',
            "serialNumber": "Serial Number",
            "productName": "Product Name",
            "brandName": "Brand Name",
            "addRecord": "Add Record",
            "finalSubmit": "Final Submit",
        },
        "sampling": {
            "sampling": "Sampling",
        },
        "foodAlert": {
            "foodAlert": "Food Alerts",
            "title": "Food Alerts History",
            "alertId": "Alert Id#",
            "type": "Type",
        },
        "reminder": {
            "reminder": "Reminder",
        },
        "completedTasks": {
            completedTasks: "Completed Tasks",
            all:"All",
            failed:"Failed",
            queued:"Queued",
            allTask: 'All Task',
            failedTask: 'Failed Task',
            date: 'Date',
            "pdfCreated":"PDF created Successfully"
        },
        "settings": {
            "settings": "Settings",
            "inspectorName":"Inspector Name",
            "position":"Position",
            "inspectionArea":'Inspection Area',
            "unit":'Unit',
            "selectLanguage":'Select Language',
            "save":'Save',
            "cancel":"Cancel",
            "oldPassword":"Old Password",
            "newPassword":'New Password',
            "retypePassword":"Retype Password",
            "editUserProfile":"Edit User Profile",
            "changePassword":"Change Password",
            "notification":'Notification',
            "logOut":"Log Out"
        },
        "bottomText": {
            "profile": "Profile",
            "tasks": "Tasks",
            "category": "Category",
            "home": "Home",
            "foodAlerts": "Food Alerts",
            "reminders": "Reminders",
            "completedTasks": "Completed Tasks",
            "settings": "Settings"
        },
        "condemnationForm": {
            title: "INPUT FOR CONDEMNATION",
            serialNumber: "Serial Number",
            productName: "Product Name",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            remarks: "Remarks",
            place: "Place",
            reason: "Reason",
            attachments: "Attachments",
            submit: "Submit",
            cancel: "Cancel",
             reject:"reject"
        },
        "samplingForm": {
            title: "Input for sampling",
            serialNumber: "Serial Number",
            sampleCollectionReason: "Sample Collection Reason",
            sampleName: "Sample Name",
            sampleDateCollectionName: "Date of Sample Collection",
            sampleStatusCollected: "Sample status when Collected",
            sampleTemp: "Sample Temperature(°C)",
            type: "Type",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            productionDate: "Production Date",
            expiryDate: "Expiry Date",
            countryOrigin: "Country of Origin",
            remainingQuantities: "Remaining Quantities",
            remarks: "Remarks",
            attachments: "Attachments",
            submit: "Submit",
            cancel: "Cancel"
        },
        "detentionForm": {
            title: "INPUT FOR DETENTION",
            serialNumber: "Serial Number",
            type: "Type",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            selectDate: "Select Date",
            productionDate: "Production Date",
            decisions: "Decisions",
            attachments: "Attachments",
            submit: "Submit",
            cancel: "Cancel",
            termsAndCondition: "I accept Terms and Conditions",
            clickToView: "Click Here to View"
        },
        "onHoldRequest": {
            onHoldRequestDetails: 'On Hold Request Details',
            inspectionId: 'Inspection ID',
            type: 'Type',
            createdBy: 'Created By',
            establishment: 'Establishments',
            reason: 'Reason',
            comments: 'Comments',
            submit: "Submit",
            cancel: "Cancel"
        },
        "requestForClosure": {
            requestForClosureDetails: 'Request for Closure details',
            inspectionId: 'Inspection ID',
            type: 'Type',
            createdBy: 'Created By',
            establishment: 'Establishments',
            reason: 'Reason',
            comments: 'Comments',
            submit: "Submit",
            cancel: "Cancel"
        },
        "foodAlerts": {
            foodAlerts: "FOOD ALERTS",
            alertNumber: "Alert Number",
            foodAlertDetails: "Food Alert Details",
            viewProductList: "View Product List",
            alertType: "Alert Type",
            alertSource: "Alert Source",
            status: "Status",
            startDate: "Start Date",
            toDate: "To Date",
            description: "Description",
            sourceAlertNumber: "Source Alert Number",
            productName: "Product Name",
            brand: "Brand",
            type: "Type",
            batch: "Batch",
            quantity: "Quantity",
            weight: "Weight",
            unit: "Unit",
            country: "Country",
            foodAlertHistory: "Food Alert History",
            viewAttachments: "View Attachments",
            printHistory: "Print History",
            productList: "Product List",
            attachment: "Attachment"
        },
        "LastRecord": {
            lastRecord: 'Last Report',
            statics: 'Statics',
            statusPieChart: 'Status Pie Chart',
            satisfactory: 'Satisfactory',
            unsatisfactory: 'Unsatisfactory',
            done: 'Done',
            about: 'About',
            taskType:'Task Type',
            creationDate:'Creation Date',
            score:'Score',
            grade:'Grade',
            action:'Action',
            businessActivity:'Business Activity',
            status:'Status',
            actualInspectionDate:'Actual Inspection Date',
            inspectionDetails:'Inspection Details',
        },
	"documentAndRecord": {
            save: 'Save',
            result: 'Result',
            finalComment: 'Final Comments',
            signHere: 'Sign Here'
        },
        "staff": {
            name: 'Name',
            contact: 'Contact',
            post: 'Post'
        },
        history: {
            stopSync: 'Stop Sync',
            reportTask: 'Report Task',
            printReport: 'Print Report',
            viewChecklist: 'View Checklist',
             "history":"HISTORY",
            "serachByEstablishment":"Search by Establishment",
            "searchByVehicle":"Search By Vehicle",
            "serviceRequest":"Service Request",
            "violation":"Violation",
            "vehicleDetails":"VehicleDetail",
            "efst":"EFST",
            "inspection":"Inspection"
        },
        "violationDetails": {
            "adhoc": "ADHOC",
            "violationList": "Violation List",
            "violationID": "Violation ID#",
            "inspectionID": "Inspection ID#",
            "status": "Status",
            "violationDetails": "Violation Details",
            "violationNumber": "Violation Number",
            "inspectionNumber": "Inspection Number",
            "createdBy": "Created By",
            "creationDate": "Creation Date",
            "status": "Status",
            "submit": "Submit",
            "cancel": "Cancel"
        },
        "scheduled": {
            "scheduled": "SCHEDULED",
            "complaints": "Complaints",
            "routineInspection": "ROUTINE INSPECTION",
            "license": "LICENSE",
            "followUp": "FOLLOW UP"
        },
               
        temporaryPermits: {
            alertTitle: 'Do you wish to perform an existing inspection or create new AdHoc Inspection ??',
            performExisting: 'Perform Existing',
            createAdhoc: 'Create Adhoc',
            serviceRequestList: 'Service Request List',
            showSr: 'Show Sr',
            tradeLicenseNumb: 'Trade License Number',
            licenseExpiryDate: 'License Expiry Date',
            mainBA: 'Main Business Activity',
            sector: 'Sector',
            custName: 'Customer Name',
            estType: 'Establishment Type',
            licenseSource: 'License Source',
            area: 'Area',
            serviceReqNum: 'Service Request Number',
            application: 'Application',
            applicationType: 'Application Type',
            closedDate: 'Closed Date',
            permitStartDate: 'Permit Start Date',
            permitEndDate: 'Permit End Date',
            city: 'City',
            requestNo:'Request No'
        },
         "adhocTask":{
            "adhocTask":"ADHOC TASKS",
            "establishment":"Establishment",
            "englishTradeName":"English Trade Name",
            "arabicTradeName":"Arabic Trade Name",
            "licenseSource":"License Source",
            "licenseNo":"License No.",
            "area":"Area",
            "sector":"Sector",
            "search":'Search',
            "createTask":"Create Task",
            "createNew":"Create New",
            "vehicle":"Vehicle",
            "placeofIssue":"Place of Issue",
            "plateNumber":"Plate Number",
            "plateCode":"Plate Code",
            "chassisNumber":"Chassis Number",
            "cancel":"Cancel",
            "establishmentName":"Establishment Name",
            "tradeLicense":"Trade License",
            "licenseSource":"License Source",
            "address":"Address",
            "establishmentDetails":"Establishment Details",
            "licenseNumber":"License Number",
            "licenseStartDate":"License Start Date",
            "licenseEndDate":"License End Date",
            "arabicEstablishmentName":"Arabic Establishment Name",
            "contactDetails":"Contact Details",
            "emailid":"Email ID",
            "onHold":"On Hold",
            "businessActivity":"Business Activity",
            "selectVehicle":"Select Vehicle",
            "taskType":"Task Type",
            "createNewTask":"Create New Task",
            "createAndView":"Create and View",
            "establishmentEngName":"Establishment English Name",
            "establishmentArName":"Establishment Arabic Name",
            "establishmentType":"Establishment Type",
            "establishmentClass":"Establishment Class",
            "plateCode":"Plate Code",
            "plateNumber":"Plate Number",
            "vehicleMake":"Vehicle Make",
            "contact":"Contact",
            "tradeLicenseNumber":"Trade License Number",
            "tradeLicenseSource":"Trade License Source",
            "createNewEstablishment":"Create New Establishment",
            "bussinessActivitynotfound":"No associated bussiness activity found"            
        },
        "serviceRequstList":{
            "serviceRequestList":"Service Request List",
            "serviceRequestNo":"Service Request No",
            "applicationType":"Application Type",
            "application":"Application", 
            "serviceRequestDetails":"Service Request Details",
            "serviceRequestNo":"Service Request No", 
            "city":"City",
            "status":"Status",
            "creationDate":"Creation Date",
            "closedDate":"Closed Date",
            "permitsStartDate":"Permit Start Date",
            "permitEndDate":"Permit End Date",
            "businessActivity":"Business Activity",
            "category":"Category", 
            "violationList":"Violation List",
            "violationNumber":"Violation Number",
            "inspectionNumber":"Inspection Number",
            "violationDetail":"Violation Details",
            "createdBy":"Created By",              
        },     

        "vehicleDetails":{
            "vehicleDetails":"Vehicle Details",
            "plateCode":"Plate Code",
            "plateNumber":"Plate Number",
            "placeOfIssue":"Place Of Issue"
        },
	"closureInspection":{
            "title": "Closure Inspection",
            "tradeName":"Trade Name",
            "licenseNo":"License No",
            "nameoffoodbusinessoperator":"Name of Food Business Operator",
            "signatureOfFood":"Signature of Food Business Operator",
            "address":"Address",
            "comment":"Comment",
            "inspectorName":"Inspector Name",
            "submit":"Submit",
            "msg":"Is this Inspection Approved?",
            "yes":"Yes",
            "no":"No"
        },
        "campaignDetails": {
            "planNumber": "Plan Number",
            "comments": "Comments",
             "planStartDate":"Plan Start Date",
            "expectedCompletionDate": "Expected Completion Date",
             "CompletionDate":"Completion Date",
            "priority": "Priority",
            "Description": "Decription",
            "startCampaign": "Start Campaign",
            "campaignPlanDetails": "Campaign Plan Details",
            "listOfEstablishment": "List Of Establishment",
            "campaign":"CAMPAIGN",
            "campaignInspection" : "Campaign Inspection",
              "view" : "View"
        },
    },

    ar: {

        "login": {
            "signIn": "تسجيل الدخول",
            "userName": "اسم المستخدم",
            "enterUserName": "ادخل اسم المستخدم",
            "password": "كلمه السر",
            "enterPassword": "أدخل كلمة المرور",
            "rememberMe": "تذكرنى",
            "forgotPassword": "هل نسيت كلمة المرور ؟",
            "dontHaveAnAccount": "ليس لديك حساب؟ ",
            "signUp": "سهلى عح",
            "thisFieldIsRequired": "هذه الخانة مطلوبه.",
            "invalidUserName": "اسم المستخدم غير صالح",
            "invalidPassword": "أدخل كلمة مرور صالحة",
            "english": "English",
            "arabic": "Arabic"
        },
        "header": {
            "login": "مخلهى",
            "smartControl": "التحكم الذكي",
            "welcome": "أهلا بك",
            "guest": "زائر"
        },
        "dashboard": {
            "myTasks": "مهامي",
            "licenses": "التراخيص",
            "cases": "حالات",
            "campaign": "حملة",
            "temporaryPermits": "تصاريح مؤقتة",
            "adhocTasks": "المهام المخصصة",
            "foodAlerts": "تنبيهات الغذاء",
            "completedTesk": "مهمة مكتملة",
            "history": "التاريخ",
            "search": "بحث",
            "sort":"صنف حسب",
            "pleaseEnterText": "حمثشسث ثىفثق فثءف"
        },
        "establishmentDetails": {
            "establishmentDetails": "تفاصيل التأسيس",
            "establishmentName": "اسم المؤسسة",
            "licenseSource": "مصدر الترخيص",
            "licenseStartDate": "تاريخ بدء الترخيص",
            "licenseEndDate": "تاريخ انتهاء الترخيص",
            "licenseNumber": "رقم الرخصة",
            "contactDetails": "بيانات المتصل",
            "address": "عنوان",
            "area": "منطقة",
            "contact": "اتصل",
            "efst": "ثبسف",
            "sector": "قطاع",
            "print":"طباعة",
            "viewChecklist":"View Checklist",
            "createPdfMsg":"إنشاء قوات الدفاع الشعبي"
        },
        "alertComponent": {
            "score": "أحرز هدفا",
            "description": "وصف",
            "nonComplaince": "عدم الامتثال",
        },
          "historyInspectionDetails": {
            "inspectionDetails": "تفاصيل التفتيش",
            "inspectionNumber": "رقم التفتيش",
            "taskType": "نوع المهمة",
            "creationDate": "تاريخ الإنشاء",
            "completionDate":"موعد الإكمال",
            "status": "الحالة",
            "businessActivity": "النشاط التجاري",
            "grade": "درجة",
            "description": "وصف",
            "priority": "أفضلية",           
            "viewChecklist":"ر هثص ؤاثؤنمهشسف"
        },
        "inspectionDetails": {
            "inspectionDetails": "تفاصيل التفتيش",
            "inspectionDetailsbtn": "تفاصيل التفتيش",
            "taskId": "معرف المهمة",
            "taskType": "نوع المهمة",
            "creationDate": "تاريخ الإنشاء",
            "businessActivity": "النشاط التجاري",
            "subbusinessActivity": "نشاط تجاري فرعي",
            "description": "وصف",
            "risk": "المخاطرة",
            "sheduledDate": "التاريخ المقرر",
            "action": "عمل",
            "startInpection": "ابدأ إلهام",
            "inspectionNo": "رقم التفتيش",
            "acknowledge": 'Acknowledge'
        },
        "myTask": {
            "myTask": "مهامي",
            "inspectionId": "التفتيش",
            "type": "نوع",
            "license": "License",
            "searchHere": "ابحث هنا"
        },
        "startInspection": {
            "startInpection": "بدء الفحص",
            "part1DesignAndStructureAndEquiment": "الجزء 1: التصميم والهيكل والمعدات",
            "updateSomething": "1. قم بتحديث شيء ما",
            "contactName": "اسم جهة الاتصال",
            "mobileNumber": "رقم الهاتف المحمول",
            "emiratesId": "هويه الإمارات",
            "evidence": "دليل",
            "license": "رخصة",
            "checklist": " الخطوة 1: قائمة التحقق",
            "submission": "الخطوة 3: التقديم",
            "documentation": "الخطوة الثانية: التوثيق والسجلات",
            "checklistSubmittedSuccessfully": "تم إرسال قائمة التحقق بنجاح",
            "checklistNotAvailable": "No Checklist",
            "condemnation": "ؤخىيثةىشفهخى",
            "detention": "يثفثىفهخى",
            "sampling": "سشةحمهىل",
            "onHoldRequest": "طلب معلق",
            "requestforClosure": "طلب الإغلاق",
            "finalResult": "النتيجة النهائية",
            "finalInspectionResult": "نتيجة الفحص النهائي",
            "totalScore": "0:مجموع النقاط",
            "grade": "E:درجة",
            "percentage": " 0:النسبة المئوية",
            "calculate": "احسب",
            "print": "طباعة",
            next: 'Next',
            back: 'Back'
        },
	"documentAndRecord":{
            signHere:"من فضلك وقع هنا.",
            save:"حفظ",
            result:"نتيجة",
            finalComment:"التعليق النهائي",
            condemnation:"إدانة",
            sampling:"أخذ العينات",
            detention:"احتجاز",
            onHoldRequest:"طلب معلق",
            requestForClosure:"طلب الإغلاق",
        },
        "contactList": {
            "contactList": "قائمة الإتصال",
            "type": "نوع",
            "name": "اسم",
            "nationality": "الجنسية",
            "mobileNumber": "رقم الهاتف المحمول",
            "relationship": "قثمشفهخىساهح",
        },
        "action": {
            "action": "عمل",
            "taskId": "معرف المهمة",
            "establishment": "مؤسسة",
            "reason": "السبب",
            "comments": "تعليقات",
            "proposedDate": "التاريخ المقترح",
            "submit": "إرسال",
            "cancel": "إلغاء"
        },
        "efstDetails": {
            "efstDetails": "ثبسف يثفشهمس",
            "foodHandlerId": "معرف معالج الطعام",
            "emiratesId": "هويه الإمارات",
            "foodHandlerName": "اسم معالج الطعام",
            "gender": "جنس",
            "passPercentage": "نسبة النجاح",
            "nationality": "الجنسية",
            "passortNumber": "رقم جواز السفر",
            "trained": "متدرب",
            "certified": "معتمد",
            "foodHandlerCount": "عدد معالج الطعام",
            "noUpdates": "لا توجد تحديثات",
            "update": "تحديث",
        },
        "profile": {
            "profileDetails": "تفاصيل الملف الشخصي",
            "guideManual": "كتيبات / أدلة",
            "inspectorName": "اسم المفتش",
            "position": "موضع",
            "inspectionArea": "منطقة التفتيش",
            "unit": "وحدة",
            "selectLanguage": "اختار اللغة",
            "fileType": "نوع الملف",
            "manualName": "الاسم اليدوي",
            "versionNumber": "رقم الإصدار"
        },
        "taskList": {
            "document": "وثيقة",
            "staff": "العاملين",
            "lastReport": "آخر تقرير",
            "history": 'التاريخ',
            "directions": "الاتجاهات",
            "routineInspection": "تفتيش روتينية",
            "followUp": "متابعة",
            "complaints": "شكاوي",
            "license": "رخصة",
            "foodAlerts": "الطعام",
            "instantViolation": "انتهاك فوري",
            "adhocTasks": "مهمة مخصصة",
            "sampling": "أخذ العينات",
            "condemnation": "إدانة",
            "detention": "احتجاز",
            "closure": "إغلاق",
            "scheduled": "المقرر",
            "adhoc": "مخصصة",
            about: "حول",
            document: "مستندات"
        },
        "detention": {
            "detention": "احتجاز",
            "condemnation": 'إدانة',
            "serialNumber": "رقم سري",
            "recordNumber": "Record No ",
            "productName": "اسم المنتج",
            "brandName": "اسم العلامة التجارية",
            "finalSubmit": "Final Submit",
            "addRecord": "إضافة سجل",
        },
        "sampling": {
            "sampling": "أخذ العينات",
        },
        "foodAlert": {
            "foodAlert": "بخخي شمثقفس",
            "title": "تاريخ التنبيهات الغذائية",
            "alertId": "معرف التنبيه #",
            "type": "نوع"
        },
        "reminder": {
            "reminder": "قثةهىيثقس",
        },
        "completedTasks": {
            completedTasks: "ؤخةحمثفثي فشسنس",
            all: 'كل مهمة',
            failed: 'مهمة فاشلة',
            date: 'تاريخ',
            queued:"Queued",
            "pdfCreated":"PDF created Successfully"
        },
        "settings": {
            "settings": "سثففهىلس",
            "inspectorName":"اسم المفتش",
            "position":"موضع",
            "inspectionArea":'منطقة التفتيش',
            "unit":'وحدة',
            "selectLanguage":'اختار اللغة',
            "save":'حفظ',
            "cancel":"إلغاء",
            "oldPassword":"كلمة المرور القديمة",
            "newPassword":'كلمة مرور جديدة',
            "retypePassword":"أعد إدخال كلمة السر",
            "editUserProfile":"تحرير ملف تعريف المستخدم",
            "changePassword":"تغيير كلمة المرور",
            "notification":'تنبيه',
            "logOut":"تسجيل خروج"
        },
        "bottomText": {
            "profile": "حقخبهمث",
            "tasks": "فشسنس",
            "category": "ؤشفثلخقغ",
            "home": "اخةث",
            "foodAlerts": "بخخي شمثقفس",
            "reminders": "قثةهىيثقس",
            "completedTasks": "ؤخةحمثفثي فشسنس",
            "settings": "سثففهىلس"
        },
        "condemnationForm": {
            "title": "مدخلات الإدانة",
            "serialNumber": "رقم سري",
            "productName": "اسم المنتج",
            "unit": "وحدة",
            "quantity": "كمية",
            "netWeight": "الوزن الصافي / صافي القيمة",
            "package": "صفقة",
            "batchNumber": "رقم الدفعة",
            "brandName": "اسم العلامة التجارية",
            "remarks": "ملاحظات",
            "place": "مكان",
            "reason": "السبب",
            "attachments": "المرفقات",
            "submit": "إرسال",
            "cancel": "إلغاء",
             reject:"رفض"
        },
        "samplingForm": {
            title: "المدخلات لأخذ العينات",
            serialNumber: "رقم سري",
            sampleCollectionReason: "سبب جمع العينة",
            sampleName: "اسم عينة",
            sampleDateCollectionName: "تاريخ جمع العينة",
            sampleStatusCollected: "حالة العينة عند جمعها",
            sampleTemp: "درجة حرارة العينة (درجة مئوية)",
            type: "نوع",
            unit: "Unit",
            quantity: "Quantity",
            netWeight: "Net Weight/Net Value",
            package: "Package",
            batchNumber: "Batch Number",
            brandName: "Brand Name",
            productionDate: "Production Date",
            expiryDate: "Expiry Date",
            countryOrigin: "بلد المنشأ",
            remainingQuantities: "الكميات المتبقية",
            remarks: "ملاحظات",
            attachments: "المرفقات",
            submit: "إرسال",
            cancel: "إلغاء"
        },
        "detentionForm": {
            "title": "مدخلات للاحتجاز",
            "serialNumber": "رقم سري",
            "type": "نوع",
            "unit": "وحدة",
            "quantity": "كمية",
            "netWeight": "الوزن الصافي / صافي القيمة",
            "package": "صفقة",
            "batchNumber": "رقم الدفعة",
            "brandName": "اسم العلامة التجارية",
            "selectDate": "حدد تاريخ",
            "productionDate": "تاريخ الإنتاج",
            "decisions": "قرارات",
            "attachments": "المرفقات",
            "submit": "إرسال",
            "cancel": "إلغاء",
            "termsAndCondition": "أنا أوافق على الأحكام و الشروط",
            "clickToView": "انقر هنا لعرض"
        },
        "onHoldRequest": {
            onHoldRequestDetails: 'تفاصيل الطلب المعلق',
            inspectionId: 'معرف التفتيش',
            type: 'نوع',
            createdBy: 'انشأ من قبل',
            establishment: 'المنشآت',
            reason: 'السبب',
            comments: 'تعليقات',
            submit: "إرسال",
            cancel: "إلغاء"
        },
        "requestForClosure": {
            requestForClosureDetails: 'طلب تفاصيل الإغلاق',
            inspectionId: 'معرف التفتيش',
            type: 'نوع',
            createdBy: 'انشأ من قبل',
            establishment: 'المنشآت',
            reason: 'السبب',
            comments: 'تعليقات',
            submit: "إرسال",
            cancel: "إلغاء"
        },
        "foodAlerts": {
            foodAlerts: "تنبيهات الطعام",
            alertNumber: "رقم التنبيه",
            foodAlertDetails: "تفاصيل التنبيه الغذائي",
            viewProductList: "عرض قائمة المنتجات",
            alertType: "نوع الانذار",
            alertSource: "نوع الانذار",
            status: "الحالة",
            startDate: "تاريخ البدء",
            toDate: "حتى الآن",
            description: "وصف",
            sourceAlertNumber: "رقم التنبيه المصدر",
            productName: "اسم المنتج",
            brand: "الماركة",
            type: "نوع",
            batch: "دفعة",
            quantity: "كمية",
            weight: "وزن",
            unit: "وحدة",
            country: "بلد",
            foodAlertHistory: "تاريخ تنبيه الغذاء",
            viewAttachments: "عرض المرفقات",
            printHistory: "تاريخ الطباعة",
            productList: "قائمة المنتجات",
            attachment: "المرفق"

        },
        "LastRecord": {
            lastRecord: 'Last Report',
            statics: 'Statics',
            statusPieChart: 'Status Pie Chart',
            satisfactory: 'Satisfactory',
            unsatisfactory: 'Unsatisfactory',
            done: 'Done',
            about: 'About',
            taskType:'Task Type',
            creationDate:'Creation Date',
            score:'Score',
            grade:'Grade',
            action:'Action',
            businessActivity:'Business Activity',
            status:'Status',
            actualInspectionDate:'Actual Inspection Date',
            inspectionDetails:'Inspection Details',
        },
        "staff": {
            name: 'اسم',
            contact: 'اتصل',
            post: 'بريد'
        },
        history: {
            stopSync: 'أوقف المزامنة',
            reportTask: 'تقرير المهمة',
            printReport: 'اطبع تقرير',
            viewChecklist: 'عرض قائمة التحقق',
             "history":"التاريخ",
            "serachByEstablishment":"البحث عن طريق المؤسسة",
            "searchByVehicle":"البحث عن طريق السيارة",
            "serviceRequest":"طلب خدمة",
            "violation":"عنيف",
            "vehicleDetails":"تفاصيل السيارة",
            "efst":"ثبسف",
            "inspection":"تفتيش"          
        },
        "violationDetails": {
            "adhoc": "مخصصة",
            "violationList": "قائمة المخالفات",
            "violationID": "معرف المخالفة #",
            "inspectionID": "معرف التفتيش #",
            "status": "الحالة",
            "violationDetails": "تفاصيل المخالفة",
            "violationNumber": "رقم المخالفة",
            "inspectionNumber": "رقم التفتيش",
            "createdBy": "انشأ من قبل",
            "creationDate": "تاريخ الإنشاء",
            "status": "الحالة",
            "submit": "إرسال",
            "cancel": "إلغاء"
        },
        "scheduled": {
            "scheduled": "المقرر",
            "complaints": "شكاوي",
            "routineInspection": "تفتيش روتينية",
            "license": "رخصة",
            "followUp": "متابعة"
        },
        temporaryPermits: {
            alertTitle: 'Do you wish to perform an existing inspection or create new AdHoc Inspection ??',
            performExisting: 'Perform Existing',
            createAdhoc: 'Create Adhoc',
            serviceRequestList: 'Service Request List',
            showSr: 'Show Sr',
            tradeLicenseNumb: 'Trade License Number',
            licenseExpiryDate: 'License Expiry Date',
            mainBA: 'Main Business Activity',
            sector: 'Sector',
            custName: 'Customer Name',
            estType: 'Establishment Type',
            licenseSource: 'License Source',
            area: 'Area',
            serviceReqNum: 'Service Request Number',
            application: 'Application',
            applicationType: 'Application Type',
            closedDate: 'Closed Date',
            permitStartDate: 'Permit Start Date',
            permitEndDate: 'Permit End Date',
            city: 'City',
            requestNo:'Request No'
        },
         "adhocTask":{
            "adhocTask":"شياخؤ فشسنس",
            "establishment":"مؤسسة",
            "englishTradeName":"الاسم التجاري الانجليزي",
            "arabicTradeName":"الاسم التجاري العربي",
            "licenseSource":"مصدر الترخيص",
            "licenseNo":"رقم الرخصة.",
            "area":"منطقة",
            "sector":"قطاع",
            "search":'بحث',
            "createTask":"إنشاء مهمة",
            "createNew":"ؤقثشفث ىثص",
             "vehicle":"مركبة",
            "placeofIssue":"مكان صدوره",
            "plateNumber":"رقم لوحة",
            "plateCode":"رمز اللوحة",
            "chassisNumber":"رقم الهيكل",
            "cancel":"إلغاء",
            "establishmentName":"اسم المؤسسة",
            "tradeLicense":"رخصة تجارية",
            "licenseSource":"مصدر الترخيص",
            "address":"عنوان",
            "establishmentDetails":"تفاصيل المنشأة",
            "licenseNumber":"رقم الرخصة",
            "licenseStartDate":"تاريخ بدء الترخيص",
            "licenseEndDate":"تاريخ انتهاء الترخيص",
            "arabicEstablishmentName":"اسم المؤسسة باللغة العربية",
            "contactDetails":"بيانات المتصل",
            "emailid":"عنوان الايميل",
            "onHold":"في الانتظار",
            "businessActivity":"النشاط التجاري",
            "selectVehicle":"اختر السيارة",
            "taskType":"نوع المهمة",
            "createNewTask":"إنشاء مهمة جديدة",
            "createAndView":"إنشاء وعرض",
            "establishmentEngName":"الاسم الانجليزي للمنشأة",
            "establishmentArName":"الاسم العربي للمنشأة",
            "establishmentType":"نوع المنشأة",
            "establishmentClass":"فئة التأسيس",
            "plateCode":"رمز اللوحة",
            "plateNumber":"رقم لوحة",
            "vehicleMake":"صناعة المركبات",
            "contact":"اتصل",
            "tradeLicenseNumber":"رقم الرخصة التجارية",
            "tradeLicenseSource":"مصدر الرخصة التجارية",
            "createNewEstablishment":"إنشاء مؤسسة جديدة"    ,
            "bussinessActivitynotfound":"No associated bussiness activity found"         
        },
        "serviceRequstList":{
            "serviceRequestList":"قائمة طلبات الخدمة",
            "serviceRequestNo":"رقم طلب الخدمة",
            "applicationType":"نوع التطبيق",
            "application":"تطبيق",  
            "serviceRequestDetails":"تفاصيل طلب الخدمة",
            "serviceRequestNo":"رقم طلب الخدمة", 
            "city":"مدينة",
            "status":"الحالة",
            "creationDate":"تاريخ الإنشاء",
            "closedDate":"تاريخ مغلق",
            "permitsStartDate":"تاريخ بدء التصريح",
            "permitEndDate":"تاريخ انتهاء التصريح",
            "businessActivity":"النشاط التجاري",  
            "category":"الفئة" ,
            "violationList":"قائمة المخالفات",
            "violationNumber":"رقم المخالفة",
            "inspectionNumber":"رقم التفتيش",
            "violationDetail":"تفاصيل المخالفة",
            "createdBy":"انشأ من قبل",       

        },
        "vehicleDetails":{
            "vehicleDetails":"تفاصيل السيارة",
            "plateCode":"رمز اللوحة",
            "plateNumber":"رقم لوحة",
            "placeOfIssue":"مكان صدوره"
        },
	"closureInspection": {
            "title": "Closure Inspection",
            "tradeName": "Trade Name",
            "licenseNo": "رقم الرخصة",
            "nameoffoodbusinessoperator": "Name of Food Business Operator",
            "signatureOfFood": "Signature",
            "address": "عنوان",
            "comment": "تعليقات",
            "inspectorName": "اسم المفتش",
            "submit": "إرسال",
            "msg": "Is this Inspection Approved?",
            "yes":"Yes",
            "no": "No"
        },
        "campaignDetails": {
            "planNumber": "Plan Number",
            "comments": "Comments",
             "planStartDate":"Plan Start Date",
            "expectedCompletionDate": "Expected Completion Date",
             "CompletionDate":"Completion Date",
            "priority": "Priority",
            "Description": "Decription",
            "startCampaign": "Start Campaign",
            "campaignPlanDetails": "Campaign Plan Details",
            "listOfEstablishment": "List Of Establishment",
            "campaign":"Campaign",
            "campaignInspection" : "Campaign Inspection",
            "view" : "View"
        },
    }
}

export default Strings;